# Assets (i.e. lambda) aren't supported to be deployed via Cloudformation Build actions. So, we'll have to run cdk deploy manually. See https://github.com/awslabs/aws-cdk/issues/1312

version: 0.2

phases:
  install:
    commands:
      - apt update
      - apt install jq
      - pip install --upgrade awscli
      - cd packages/livejam
      - npm install -g yarn
      - yarn install
  build:
    commands:
      - yarn cdk:build
      - yarn cdk:deploy -- --require-approval never
      - yarn cdk:output:env
      - yarn build
      - yarn deploy

cache:
  paths:
    - "packages/livejam/node_modules/**/*"
