# Assets (i.e. lambda) aren't supported to be deployed via Cloudformation Build actions. So, we'll have to run cdk deploy manually. See https://github.com/awslabs/aws-cdk/issues/1312

version: 0.2

phases:
  install:
    commands:
      - cd packages/livejam
      - npm install -g yarn
      - yarn install
  build:
    commands:
      - env
      - echo boom
      - yarn build
      - yarn cdk:build
      - yarn cdk:deploy
